### ISSUE TITLE
TODOS

### ISSUE THREAD

**Issue by magicdawn** [magicdawn/magicdawn#27]
毕业了, 做做规划:
## 长期
- [ ] c/cpp native addon
- [ ] libuv
- [ ] <del>electron</del>
## 近期
- [x] handlebars 模板, layout
- [x] browserify
- [x] koa/impress-router
## Book
- [ ] 编译原理
- [ ] 算法

**Comment by magicdawn** [comment]
## TODOS
 希望我的年终总结是这样的

- [ ] 玩熟了 highcharts, 熟悉svg
- [ ] 玩熟了koa, 产出xxx xxx plugins , 并且有 100% 覆盖率
- [ ] 玩熟了browserify, 前端架构上有较深理解 webpack 后续再说

生活
- [ ] 完成200 公里? 现有36 公里, 剩下4个月, 每月50公里, 每周 12.5公里 = 6.25 * 2 可以完成
- [ ] keep, 驼背改善每天+1 , 其他?
- [ ] 论语
- [ ] 辛词

**Comment by magicdawn** [comment]
## Day 20151013

好好整理下:

### 目前
- I have ran 97 kms.
- I'm familar with koa/browserify.

## future
- gulp/vinyl related
- CSS Definitive Guide & CSS Garden
- cnbogs 汤姆大叔 / JS Garden 中英 / JS Good Parts / Js Deginitive Guide

Plans Great. Acts FAST.

**Comment by magicdawn** [comment]
## Less hunt

- HTTP definetive Guide
- node.js  net.js / _http_*.js _stream_*.js

**Comment by magicdawn** [comment]
## FE
- [ ] react 生态系统
- [ ] 复习 css

## BE
- [ ] mysql复习 & 提高
      - [ ] sql复习, 触发器/存储过程
      - [ ] 分库分表...
      - [ ] binlog 等, 事务, 锁
- [ ] redis
      - [ ] commands
      - [ ] internal
      - [ ] ioredis 库代码
      - [ ] redis 代码
- [ ] C/C++
